### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by alnimu** [kotchuprik/yii2-odnoklassniki-authclient#2]
1. There is no properties consumerKey, consumerSecret in class, so Exception appears:
   Setting unknown property: kotchuprik\authclient\Odnoklassniki::consumerKey
2. Even if they was there they not used in any class method.
3. Update readme.
4. Update component in composer

**Comment by chuprik** [comment]
Sorry for the problem. It's my mistake. I've updated the readme https://github.com/kotchuprik/yii2-odnoklassniki-authclient/blob/master/README.md

**Comment by alnimu** [comment]
It's OK now))) Thanks!
Can you please update composer component ?

**Comment by chuprik** [comment]
done. please create a new issue if you will have a new problem with component :)

**Comment by alnimu** [comment]
Thanks! You save my day)
