### ISSUE TITLE
PARAM_API_KEY : No application key

### ISSUE THREAD

**Issue by ghost** [kotchuprik/yii2-odnoklassniki-authclient#5]
Error:

>  'error_code' => int 101
>  'error_msg' => string 'PARAM_API_KEY : No application key' (length=34)
>  'error_data' => null

Fix:

>  protected function initUserAttributes()
>    {
>        $params = [];
>        $params['access_token'] = $this->accessToken->getToken();
>        $params['application_key'] = $this->applicationKey;
>        $params['sig'] = $this->sig($params, $params['access_token'], $this->clientSecret);
>        return $this->api('api/users/getCurrentUser', 'GET', $params);
>    }

**Comment by isudakoff** [comment]
Я получаю точно такую же ошибку. Что я могу делать неправильно?
```php
    $client = new Odnoklassniki;
        ... // Тут идёт присвоение access_token, которые хранятся у меня в БД
    $client->api('api/stream/publish', 'POST', ['message' => "Hello world!"]);
```

**Comment by chuprik** [comment]
@iSudakoff версия экстеншна последняя?

**Comment by isudakoff** [comment]
@kotchuprik Да

**Comment by chuprik** [comment]
@iSudakoff ничем не смогу помочь, необходимо смотреть правильность подключения, смотреть все ли запросы отрабатывают и были ли изменения в апи одноклассников

**Comment by chuprik** [comment]
как вариант, могу порекомендовать попробовать изменения из не смерженного реквеста https://github.com/kotchuprik/yii2-odnoklassniki-authclient/pull/7
